// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared_Clipboard_Backend.Data;

#nullable disable

namespace Shared_Clipboard_Backend.Migrations
{
    [DbContext(typeof(MySQLDbContext))]
    [Migration("20260603125457_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Shared_Clipboard_Backend.Models.Dto.ClipboardItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("ClipboardItemEntity");
                });

            modelBuilder.Entity("Shared_Clipboard_Backend.Models.Dto.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OSName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Shared_Clipboard_Backend.Models.Dto.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared_Clipboard_Backend.Models.Dto.ClipboardItemEntity", b =>
                {
                    b.HasOne("Shared_Clipboard_Backend.Models.Dto.UserEntity", null)
                        .WithMany("Clipboard")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("Shared_Clipboard_Backend.Models.Dto.DeviceEntity", b =>
                {
                    b.HasOne("Shared_Clipboard_Backend.Models.Dto.UserEntity", null)
                        .WithMany("Devices")
                        .HasForeignKey("UserEntityId");
                });

            modelBuilder.Entity("Shared_Clipboard_Backend.Models.Dto.UserEntity", b =>
                {
                    b.Navigation("Clipboard");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
